"""Add auth_level to User model

Revision ID: 5a16a2ed69fc
Revises: c6f8dd689442
Create Date: 2024-06-11 15:48:11.665740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a16a2ed69fc'
down_revision = 'c6f8dd689442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user2',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=128), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=False),
        sa.Column('password', sa.String(length=128), nullable=False),
        sa.Column('organization', sa.String(length=128), nullable=False),
        sa.Column('auth_level', sa.String(length=128), nullable=False),
        sa.Column('aligner', sa.Boolean(), nullable=False),
        sa.Column('diffexp', sa.Boolean(), nullable=False),
        sa.Column('qc_pages', sa.Boolean(), nullable=False),
        sa.Column('ssg', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user2')
    # ### end Alembic commands ###
