"""empty message

Revision ID: bace5e015300
Revises: 467d1a90a22f
Create Date: 2024-07-11 15:27:05.300709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bace5e015300'
down_revision = '467d1a90a22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_path', sa.String(length=200), nullable=True))
        batch_op.alter_column('organization',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('auth_level',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('aligner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('diffexp',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('qc_pages',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('ssg',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_unique_constraint('username', ['username'])
        batch_op.create_unique_constraint('email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('username', type_='unique')
        batch_op.drop_constraint('email', type_='unique')
        batch_op.alter_column('ssg',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('qc_pages',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('diffexp',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('aligner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('auth_level',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('organization',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('user_path')

    # ### end Alembic commands ###
